- hosts: src_server
  become: false
  gather_facts: no
  tasks:
    - name: Ping from source to destination
      shell: ping -c3 {{dst_server_ip}} | tee -a /home/user/src_ping
      register: src_ping
    - name: Print ping result
      debug:
        var: src_ping.stdout
